name: Build
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      gar_repository:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2

      - uses: docker/setup-buildx-action@v3

      - name: Log in to GAR
        run: gcloud auth configure-docker ${{ inputs.gar_repository }} --quiet

      - id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile.amd64
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.IMAGE_NAME_GAR }}:latest
